import { useCallback, useState } from "react";
import WordReveal from "./WordReveal";

// Polished "Apple keynote generator" lab. Preview fills the stage; controls
// dock to a slim sidebar. Built for cutting scenes in a 3-minute hackathon
// demo video — the stage is a fixed 16:9 box so screen-recording the preview
// crops cleanly.

const PRESETS = [
  "The model hears the borrowed words.",
  "It misses the Hiligaynon.",
  "Overall WER hides which language failed.",
  "Sugidanon turns an invisible failure into a measurable benchmark.",
  "Measuring what speech AI leaves in the dark.",
];

const DEFAULTS = {
  phrase: PRESETS[0],
  mode: "dark",
  fontSize: 64,
  wordDelay: 120,
  duration: 700,
  rise: 18,
};

function genHtml(s) {
  const words = s.phrase.split(/\s+/).filter(Boolean);
  const fg = s.mode === "dark" ? "#f5f5f7" : "#1d1d1f";
  const bg = s.mode === "dark" ? "#000000" : "#ffffff";
  const spans = words
    .map(
      (w, i) =>
        `    <span class="wr-word" style="animation-delay:${(
          (i * s.wordDelay) /
          1000
        ).toFixed(3)}s">${w}</span>`
    )
    .join("\n");
  return `<!-- Apple-style word reveal — generated by Sugidanon WordRevealLab -->
<div class="wr-stage">
  <div class="wr-phrase">
${spans}
  </div>
</div>

<style>
.wr-stage{
  display:flex; align-items:center; justify-content:center;
  width:100%; aspect-ratio:16/9; background:${bg};
}
.wr-phrase{
  display:flex; flex-wrap:wrap; gap:0 ${Math.round(s.fontSize * 0.28)}px;
  justify-content:center; max-width:85%; text-align:center; line-height:1.15;
  color:${fg}; font-size:${s.fontSize}px; font-weight:600; letter-spacing:-0.02em;
  font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",Helvetica,Arial,sans-serif;
}
.wr-word{
  display:inline-block; white-space:pre;
  opacity:0; transform:translateY(${s.rise}px); filter:blur(6px);
  animation:wr-rise ${(s.duration / 1000).toFixed(3)}s cubic-bezier(0.16,1,0.3,1) forwards;
}
@keyframes wr-rise{
  to{ opacity:1; transform:translateY(0); filter:blur(0); }
}
</style>`;
}

function genReact(s) {
  return `import WordReveal from "../components/WordReveal";

<WordReveal
  phrase=${JSON.stringify(s.phrase)}
  mode=${JSON.stringify(s.mode)}
  fontSize={${s.fontSize}}
  wordDelay={${s.wordDelay}}
  duration={${s.duration}}
  rise={${s.rise}}
/>`;
}

function Field({ label, hint, children }) {
  return (
    <label style={{ display: "block", marginBottom: 18 }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          fontSize: 12,
          color: "#86868b",
          marginBottom: 6,
          textTransform: "uppercase",
          letterSpacing: "0.06em",
        }}
      >
        <span>{label}</span>
        {hint != null && <span style={{ color: "#bbb" }}>{hint}</span>}
      </div>
      {children}
    </label>
  );
}

const range = {
  width: "100%",
  accentColor: "#0071e3",
};

export default function WordRevealLab() {
  const [s, setS] = useState(DEFAULTS);
  const [playKey, setPlayKey] = useState(0);
  const [codeTab, setCodeTab] = useState("html"); // "html" | "react"
  const [copied, setCopied] = useState(false);

  const set = (k) => (v) => setS((p) => ({ ...p, [k]: v }));
  const replay = useCallback(() => setPlayKey((k) => k + 1), []);

  const code = codeTab === "html" ? genHtml(s) : genReact(s);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "1fr 340px",
        minHeight: "100vh",
        background: "#f5f5f7",
        fontFamily:
          '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Helvetica, Arial, sans-serif',
        color: "#1d1d1f",
      }}
    >
      {/* Stage */}
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          padding: 32,
          gap: 20,
        }}
      >
        <div
          style={{
            position: "relative",
            width: "100%",
            maxWidth: 1100,
            aspectRatio: "16 / 9",
            background: s.mode === "dark" ? "#000" : "#fff",
            borderRadius: 14,
            boxShadow: "0 24px 60px rgba(0,0,0,0.18)",
            overflow: "hidden",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <WordReveal {...s} playKey={playKey} />
          <span
            style={{
              position: "absolute",
              top: 12,
              left: 14,
              fontSize: 11,
              letterSpacing: "0.08em",
              color: s.mode === "dark" ? "#48484a" : "#c7c7cc",
            }}
          >
            16:9 PREVIEW
          </span>
        </div>

        <button
          onClick={replay}
          style={{
            padding: "10px 26px",
            fontSize: 15,
            borderRadius: 980,
            border: "none",
            background: "#0071e3",
            color: "#fff",
            cursor: "pointer",
            fontWeight: 500,
          }}
        >
          ↻ Replay
        </button>
      </main>

      {/* Controls */}
      <aside
        style={{
          background: "#fff",
          borderLeft: "1px solid #e5e5ea",
          padding: "28px 24px",
          overflowY: "auto",
          maxHeight: "100vh",
        }}
      >
        <h1 style={{ fontSize: 20, fontWeight: 600, margin: "0 0 4px" }}>
          Word Reveal Lab
        </h1>
        <p style={{ fontSize: 13, color: "#86868b", margin: "0 0 24px" }}>
          Apple-style phrase reveal for Sugidanon demo scenes.
        </p>

        <Field label="Phrase">
          <textarea
            value={s.phrase}
            onChange={(e) => set("phrase")(e.target.value)}
            rows={3}
            style={{
              width: "100%",
              resize: "vertical",
              padding: 10,
              borderRadius: 10,
              border: "1px solid #d2d2d7",
              fontSize: 14,
              fontFamily: "inherit",
            }}
          />
        </Field>

        <Field label="Presets">
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {PRESETS.map((p) => (
              <button
                key={p}
                onClick={() => {
                  set("phrase")(p);
                  replay();
                }}
                style={{
                  textAlign: "left",
                  padding: "8px 10px",
                  fontSize: 12.5,
                  borderRadius: 8,
                  border: "1px solid #e5e5ea",
                  background: s.phrase === p ? "#f0f7ff" : "#fafafa",
                  cursor: "pointer",
                  lineHeight: 1.3,
                }}
              >
                {p}
              </button>
            ))}
          </div>
        </Field>

        <Field label="Background">
          <div style={{ display: "flex", gap: 8 }}>
            {["light", "dark"].map((m) => (
              <button
                key={m}
                onClick={() => set("mode")(m)}
                style={{
                  flex: 1,
                  padding: "8px 0",
                  fontSize: 13,
                  borderRadius: 8,
                  textTransform: "capitalize",
                  cursor: "pointer",
                  border:
                    s.mode === m ? "1px solid #0071e3" : "1px solid #d2d2d7",
                  background: s.mode === m ? "#0071e3" : "#fff",
                  color: s.mode === m ? "#fff" : "#1d1d1f",
                }}
              >
                {m}
              </button>
            ))}
          </div>
        </Field>

        <Field label="Font size" hint={`${s.fontSize}px`}>
          <input
            type="range"
            min={24}
            max={120}
            value={s.fontSize}
            onChange={(e) => set("fontSize")(Number(e.target.value))}
            style={range}
          />
        </Field>

        <Field label="Word delay" hint={`${s.wordDelay}ms`}>
          <input
            type="range"
            min={0}
            max={400}
            step={10}
            value={s.wordDelay}
            onChange={(e) => set("wordDelay")(Number(e.target.value))}
            style={range}
          />
        </Field>

        <Field label="Duration" hint={`${s.duration}ms`}>
          <input
            type="range"
            min={200}
            max={1600}
            step={50}
            value={s.duration}
            onChange={(e) => set("duration")(Number(e.target.value))}
            style={range}
          />
        </Field>

        <Field label="Rise distance" hint={`${s.rise}px`}>
          <input
            type="range"
            min={0}
            max={60}
            value={s.rise}
            onChange={(e) => set("rise")(Number(e.target.value))}
            style={range}
          />
        </Field>

        {/* Code export */}
        <div style={{ marginTop: 8 }}>
          <div style={{ display: "flex", gap: 6, marginBottom: 8 }}>
            {["html", "react"].map((t) => (
              <button
                key={t}
                onClick={() => setCodeTab(t)}
                style={{
                  flex: 1,
                  padding: "6px 0",
                  fontSize: 12,
                  borderRadius: 8,
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                  cursor: "pointer",
                  border: "1px solid #d2d2d7",
                  background: codeTab === t ? "#1d1d1f" : "#fff",
                  color: codeTab === t ? "#fff" : "#1d1d1f",
                }}
              >
                {t === "html" ? "HTML/CSS" : "React"}
              </button>
            ))}
          </div>
          <pre
            style={{
              maxHeight: 180,
              overflow: "auto",
              background: "#1d1d1f",
              color: "#e5e5ea",
              padding: 12,
              borderRadius: 10,
              fontSize: 11,
              lineHeight: 1.5,
              margin: 0,
            }}
          >
            {code}
          </pre>
          <button
            onClick={copy}
            style={{
              width: "100%",
              marginTop: 8,
              padding: "9px 0",
              fontSize: 13,
              borderRadius: 980,
              border: "none",
              background: copied ? "#34c759" : "#1d1d1f",
              color: "#fff",
              cursor: "pointer",
            }}
          >
            {copied ? "✓ Copied" : "Copy code"}
          </button>
        </div>
      </aside>
    </div>
  );
}
